spring:
  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/struts?useSSL=false&allowPublicKeyRetrieval=true&user=root&password=aditya
    user: root
    password : aditya

  security:
    user:
      name: aditya
      password : aditya

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /data
  endpoint:
    health:
      show-details : always